### ISSUE TITLE
Incomplete sentence in documentation

### ISSUE THREAD

**Issue by ModProg** [dnaka91/unidirs#3]
> Compare the executing user’s account name against the application name to detect the service mode.
> It is common to create a separate

https://github.com/dnaka91/unidirs/blob/main/src/simple.rs#L53

**Comment by dnaka91** [comment]
Whoops, how did that happen :sweat_smile:. I just noticed there is some incomplete table as well. Will update that real quick.

**Comment by dnaka91** [comment]
Just released a new version which completes the sentence and a few other left-out spots. Thank you for letting me know about the incomplete sentence.
